package br.com.fit.app;

import android.app.*;import android.os.*;import android.graphics.*;import android.graphics.drawable.*;import android.view.*;import android.widget.*;import java.util.*;

public class MainActivity extends Activity{
 int BG=Color.rgb(7,21,29), CARD=Color.rgb(18,39,54), CARD2=Color.rgb(26,54,73), GOLD=Color.rgb(255,211,107), MUTED=Color.rgb(173,199,214);
 LinearLayout root, content; String tela="inicio", treino="push", ativo=""; long inicio=0; TextView cron; Handler h=new Handler(); HashSet<String> feitos=new HashSet<>();
 String[][] dias={{"push","Push","Peito + Ombros + Tríceps"},{"pull","Pull","Costas + Bíceps"},{"legs","Legs","Pernas"},{"push2","Push Tríceps","Ênfase em Tríceps"},{"pull2","Pull Bíceps","Ênfase em Bíceps"},{"arms","Arm Day","Braços + Abdômen"}};
 Runnable tick=new Runnable(){public void run(){ if(inicio>0&&cron!=null){ long t=System.currentTimeMillis()-inicio; if(t>120L*60L*1000L){Toast.makeText(MainActivity.this,"Treino desconsiderado: passou de 120 minutos.",1).show(); inicio=0; ativo=""; feitos.clear(); draw(); return;} cron.setText(fmt(t)); h.postDelayed(this,1000); } }};
 public void onCreate(Bundle b){super.onCreate(b); draw();}
 void draw(){root=new LinearLayout(this);root.setOrientation(LinearLayout.VERTICAL);root.setBackgroundColor(BG); LinearLayout top=new LinearLayout(this);top.setPadding(dp(18),dp(14),dp(18),dp(10));top.addView(txt("🏋️ FIT",28,GOLD,true));root.addView(top); ScrollView sv=new ScrollView(this);content=new LinearLayout(this);content.setOrientation(LinearLayout.VERTICAL);content.setPadding(dp(16),dp(10),dp(16),dp(90));sv.addView(content);root.addView(sv,new LinearLayout.LayoutParams(-1,0,1)); if(tela.equals("inicio"))home(); else if(tela.equals("treinos"))workout(); else if(tela.equals("evolucao"))evol(); else hist(); nav(); setContentView(root);} 
 void home(){ LinearLayout c=card(); c.addView(txt("Boa noite 👋",16,MUTED,false)); c.addView(txt("Treine forte, registre simples.",27,Color.WHITE,true)); c.addView(txt("Plano anual com treinos livres e registro semanal.",15,MUTED,false)); content.addView(c); LinearLayout t=card(); t.addView(txt("Meus treinos",23,Color.WHITE,true)); for(String[] d:dias){Button b=btn(d[1]+"\n"+d[2]); b.setGravity(Gravity.CENTER_VERTICAL|Gravity.LEFT); b.setOnClickListener(v->{treino=d[0]; tela="treinos"; draw();}); t.addView(b,new LinearLayout.LayoutParams(-1,dp(66)));} content.addView(t);}
 void workout(){ HorizontalScrollView hs=new HorizontalScrollView(this); LinearLayout chips=new LinearLayout(this); for(String[] d:dias){Button b=btn(d[1]); b.setOnClickListener(v->{treino=d[0]; draw();}); chips.addView(b);} hs.addView(chips); content.addView(hs); LinearLayout cab=card(); cab.addView(txt(title(treino),24,Color.WHITE,true)); cab.addView(txt(sub(treino),15,MUTED,false)); boolean on=ativo.equals(treino); if(on){cron=txt("00:00:00",28,GOLD,true);cab.addView(cron);h.post(tick);Button f=btn("✅ Finalizar treino");f.setOnClickListener(v->{Toast.makeText(this,"Treino registrado.",1).show();inicio=0;ativo="";feitos.clear();draw();});cab.addView(f);Button can=btn("Cancelar treino");can.setOnClickListener(v->{inicio=0;ativo="";feitos.clear();draw();});cab.addView(can);}else{Button s=btn("▶ Iniciar treino");s.setOnClickListener(v->{ativo=treino;inicio=System.currentTimeMillis();feitos.clear();draw();});cab.addView(s);} content.addView(cab); for(Ex e:exs(treino)) exCard(e,on); LinearLayout cardio=card();cardio.addView(txt("❤️ Cardio ao final",22,Color.WHITE,true));cardio.addView(txt("Segunda e quinta: 20 min. Sábado: 25–30 min. Domingo opcional.",15,MUTED,false));CheckBox cb=new CheckBox(this);cb.setText("Cardio concluído");cb.setTextColor(Color.WHITE);cardio.addView(cb);content.addView(cardio);}
 void exCard(Ex e,boolean on){ LinearLayout c=card(); if(feitos.contains(e.n)){c.addView(txt("✅ "+e.n,21,Color.WHITE,true));content.addView(c);return;} LinearLayout r=new LinearLayout(this);r.setOrientation(LinearLayout.HORIZONTAL); LinearLayout info=new LinearLayout(this);info.setOrientation(LinearLayout.VERTICAL); info.addView(txt(e.n,21,Color.WHITE,true));info.addView(txt(e.s+" séries × "+e.r,17,GOLD,true));info.addView(txt("Orientação: execução controlada, amplitude completa e 1–2 reps na reserva.",14,MUTED,false));info.addView(txt("Progressão: bateu o topo das reps em todas as séries, aumente 2,5–5%.",14,MUTED,false));CheckBox ch=new CheckBox(this);ch.setText("Concluir exercício");ch.setTextColor(Color.WHITE);ch.setEnabled(on);ch.setOnCheckedChangeListener((b,m)->{if(m){feitos.add(e.n);draw();}});info.addView(ch);r.addView(info,new LinearLayout.LayoutParams(0,-2,1));Button vid=btn("🎥 Vídeo");vid.setOnClickListener(v->Toast.makeText(this,"Área de vídeos será ativada na próxima versão.",1).show());r.addView(vid,new LinearLayout.LayoutParams(dp(105),dp(58)));c.addView(r);content.addView(c);}
 void evol(){LinearLayout c=card();c.addView(txt("📏 Evolução",24,Color.WHITE,true));String[] campos={"Peso kg","Braço contraído cm","Cintura cm","Peitoral cm","Coxa cm"};for(String s:campos){EditText e=new EditText(this);e.setHint(s);e.setHintTextColor(MUTED);e.setTextColor(Color.WHITE);c.addView(e);}c.addView(btn("Salvar medida"));content.addView(c);} void hist(){LinearLayout c=card();c.addView(txt("🏆 Histórico",24,Color.WHITE,true));c.addView(txt("Histórico persistente será ampliado na próxima versão.",15,MUTED,false));content.addView(c);} 
 ArrayList<Ex> exs(String k){ArrayList<Ex> l=new ArrayList<>(); if(k.equals("push")){add(l,"Supino reto",5,"10–12");add(l,"Supino inclinado halteres",5,"10–12");add(l,"Crucifixo máquina",4,"12–15");add(l,"Crossover",3,"12–15");add(l,"Desenvolvimento halteres",5,"10–12");add(l,"Elevação lateral",4,"12–15");add(l,"Tríceps pulley",4,"12–15");add(l,"Tríceps francês",4,"12–15");} else if(k.equals("pull")){add(l,"Puxada aberta",5,"10–12");add(l,"Remada baixa",5,"10–12");add(l,"Remada unilateral",5,"10–12");add(l,"Pulldown",4,"12–15");add(l,"Rosca direta",4,"12–15");add(l,"Rosca martelo",3,"12–15");} else if(k.equals("legs")){add(l,"Agachamento Smith",5,"10–12");add(l,"Leg press",5,"10–12");add(l,"Mesa flexora",4,"12–15");add(l,"Stiff",4,"12–15");add(l,"Panturrilha em pé",5,"15–20");add(l,"Panturrilha sentada",5,"15–20");} else if(k.equals("push2")){add(l,"Supino inclinado",4,"10–12");add(l,"Crossover",4,"12–15");add(l,"Desenvolvimento máquina",4,"10–12");add(l,"Elevação lateral",4,"12–15");add(l,"Tríceps testa",5,"10–12");add(l,"Tríceps corda",5,"12–15");add(l,"Mergulho banco",3,"até quase falha");} else if(k.equals("pull2")){add(l,"Puxada neutra",5,"10–12");add(l,"Remada articulada",5,"10–12");add(l,"Rosca Scott",5,"12–15");add(l,"Rosca inclinada",5,"12–15");add(l,"Rosca concentrada",4,"12–15");add(l,"Rosca inversa",2,"12–15");} else {add(l,"Rosca barra W",4,"12–15");add(l,"Rosca alternada",4,"12–15");add(l,"Rosca martelo cruzada",4,"12–15");add(l,"Tríceps pulley",4,"12–15");add(l,"Francês unilateral",4,"12–15");add(l,"Tríceps corda",4,"12–15");add(l,"Prancha",4,"60–90 s");add(l,"Abdominal infra",4,"20–25");add(l,"Crunch",4,"20–25");} return l;} void add(ArrayList<Ex> l,String n,int s,String r){l.add(new Ex(n,s,r));}
 void nav(){LinearLayout m=new LinearLayout(this);m.setOrientation(LinearLayout.HORIZONTAL);m.setBackgroundColor(Color.rgb(5,16,22));String[][] it={{"inicio","Início"},{"treinos","Treinos"},{"evolucao","Evolução"},{"historico","Histórico"}};for(String[] x:it){Button b=btn(x[1]);b.setOnClickListener(v->{tela=x[0];draw();});m.addView(b,new LinearLayout.LayoutParams(0,dp(68),1));}root.addView(m);} String title(String k){for(String[] d:dias)if(d[0].equals(k))return d[1];return "Treino";}String sub(String k){for(String[] d:dias)if(d[0].equals(k))return d[2];return "";}
 LinearLayout card(){LinearLayout l=new LinearLayout(this);l.setOrientation(LinearLayout.VERTICAL);l.setPadding(dp(16),dp(14),dp(16),dp(14));GradientDrawable g=new GradientDrawable();g.setColor(CARD);g.setCornerRadius(dp(22));g.setStroke(1,Color.rgb(48,82,106));l.setBackground(g);LinearLayout.LayoutParams p=new LinearLayout.LayoutParams(-1,-2);p.setMargins(0,dp(8),0,dp(10));l.setLayoutParams(p);return l;} Button btn(String s){Button b=new Button(this);b.setText(s);b.setAllCaps(false);b.setTextColor(Color.WHITE);b.setTextSize(14);GradientDrawable g=new GradientDrawable();g.setColor(CARD2);g.setCornerRadius(dp(14));g.setStroke(1,Color.rgb(61,94,119));b.setBackground(g);return b;} TextView txt(String s,int size,int color,boolean bold){TextView t=new TextView(this);t.setText(s);t.setTextSize(size);t.setTextColor(color);t.setPadding(0,dp(4),0,dp(4));if(bold)t.setTypeface(Typeface.DEFAULT_BOLD);return t;} String fmt(long ms){long s=ms/1000,h=s/3600,m=(s%3600)/60,sec=s%60;return String.format(Locale.US,"%02d:%02d:%02d",h,m,sec);} int dp(int v){return (int)(v*getResources().getDisplayMetrics().density);} static class Ex{String n,r;int s;Ex(String n,int s,String r){this.n=n;this.s=s;this.r=r;}}
}
